function work_checklist --description "Print manual post-install checklist for work machines"
    echo "Work machine — manual post-install checklist"
    echo ""
    echo "These steps can't be automated by chezmoi (network-gated, browser flows,"
    echo "or per-user MFA enrollment). Tick each one off after running install.sh."
    echo ""
    echo "  [ ] CloudMFA enrollment"
    echo "        Open: https://aka.ms/CloudMFA"
    echo "        Required for corporate SSO; resolves only on the work network/VPN."
    echo ""
    echo "  [ ] YubiKey: enroll for SSH + Git signing"
    echo "        Run:  yk_enroll"
    echo "        Then: yk_enroll --rotate-pin   # if FIPS, change the factory PIN"
    echo ""
    echo "  [ ] Add YubiKey SSH pubkey(s) to GitHub"
    echo "        Run:  gh ssh-key add ~/.ssh/id_ed25519_sk_<serial>.pub \\"
    echo "                --title \"\$(hostname -s)-yk-<serial>\""
    echo ""
    echo "  [ ] Sign in to GitHub CLI:        gh auth login"
    echo "  [ ] Sign in to Azure CLI:         az login"
    echo "  [ ] Sign in to 1Password CLI:     op signin   (if used)"
    echo ""
    echo "Re-run `work_checklist` any time to see this list again."
end
