#!/bin/bash

brewup() {
  # Spotify auto-updater is fast & solid, 1Password auto-updater experience is less intrusive
  local excluded_casks="spotify|1password"

  echo "=== Running brew update ==="
  brew update || { echo "brew update failed"; return 1; }
  echo "\n=== Regular cask updates ==="
  brew upgrade --cask || { echo "brew cask update failed"; return 1; }
  echo "\n=== Regular brew updates ==="
  brew upgrade || { echo "brew upgrade failed"; return 1; }
  echo "\n=== Additional updates requiring --greedy flag ==="

  casks_to_upgrade=$(brew outdated --cask --greedy | grep -vE "$excluded_casks" | awk '!/^==>/ && NF')

  if [[ -n "$casks_to_upgrade" ]]; then
    echo "$casks_to_upgrade"
    echo "\n=== Would you like to proceed with greedy updates (excluding $excluded_casks)? (y/n) ==="
    read -r response

    if [[ "$response" =~ ^[Yy]$ ]]; then
      echo "$casks_to_upgrade" | xargs -n1 brew upgrade --cask || { echo "Failed to upgrade one or more casks"; return 1; }
    else
      echo "Greedy updates skipped"
    fi
  else
    echo "No additional updates available with --greedy"
  fi
}
