#!/bin/bash

generate-passwords() {
  if [ "$#" -ne 1 ]; then
    echo "Usage: generate-passwords <amount of characters>"
    echo "Assuming 64 characters:\n"
    pass_length=64
  else
    pass_length=$1
  fi

  for i in {1..5};
    do (tr -cd '[:alnum:]' < /dev/urandom | fold -w${pass_length}| head -n 1);
  done
}
