#!/bin/bash

get-key-value() {
    KEY="$1"
    FILE="$2"

    # Check if the file exists, if not, create it
    if [ ! -f "${FILE}" ]; then
        echo "The file '${FILE}' does not exist. Therefore, we can't find key '${KEY}'"
        return 1
    fi

    # Check if the key exists in the file
    if grep -q "^${KEY}=" "${FILE}"; then
        VALUE=$(sed -n "s/^${KEY}=//p" "${FILE}")
        echo $VALUE
        return 0
    else
        echo "The key '${KEY}' was not found in the file '${FILE}'"
        return 1
    fi
}
