#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

make_zsh_default_shell () {
	# Check zsh is not already the default shell
	if ! grep -q "^$USER.*$HOME:$(which zsh)$" /etc/passwd
	then
		# Check zsh is installed, if not exit with warning
		if ! which zsh &> /dev/null
		then
			fail "Zsh is needed. Please install it via your prefered package manager."
		fi

		# If zsh is not listed as a shell, list it
		if ! grep -q "^$(which zsh)$" /etc/shells
		then
			info "Adding zsh to the list of shells (/etc/shells)"
			sudo sh -c 'echo /usr/local/bin/zsh >> /etc/shells'
		fi

		info "Making zsh default shell"
    sudo chsh -s $(which zsh) $(whoami)
	fi
}

choice() {
    if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
      echo "Usage: choice <options>"
      echo "Example: choice apple pear"
      return 0
    fi

    if [[ $# < 2 ]]; then
      echo "Error: Invalid number of choices."
      echo "Use -h or --help flag for usage information."
      return 1
    fi

    select opt in "$@"; do
      if [[ -n $opt ]]; then
          echo "$opt"
          break
      fi
    done
}

get-key-value() {
    KEY="$1"
    FILE="$2"

    # Check if the file exists, if not, create it
    if [ ! -f "${FILE}" ]; then
        info "The file '${FILE}' does not exist. Therefore, we can't find key '${KEY}'"
        return 1
    fi

    # Check if the key exists in the file
    if grep -q "^${KEY}=" "${FILE}"; then
        VALUE=$(sed -n "s/^${KEY}=//p" "${FILE}")
        echo $VALUE
        return 0
    else
        info "The key '${KEY}' was not found in the file '${FILE}'"
        return 1
    fi
}

get_dotfiles_install_mode () {
  shopt -s nocasematch
  set +e # Temp undo set -e so that we can catch the error
  VALUE=$(get-key-value DOTFILES_INSTALL_MODE ~/.env)
  if [ $? != 1 ]; then
    set -e
    echo $VALUE
    return $?
  fi

  # Reset error handling
  set -e

  if [[ $- == *i* ]]; then
    # Always install minimal version when running non-interactive
    echo "minimal"
  elif [[ $(systemd-detect-virt) == 'wsl' ]]; then
    # Install complete version with WSL
    echo "complete"
  elif [[ $OSTYPE == 'darwin'* ]]; then
    # Install complete version with MacOS
    echo "complete"
  elif [[ $HOST == 'SVL'* ]]; then
    # Install complete version on servers
    echo "minimal"
  else
    # Let the user choose
    choice "minimal" "complete"
    return $?
  fi
}

info "Configuring install mode"
DOTFILES_INSTALL_MODE=$(get_dotfiles_install_mode)
success "Install mode is $DOTFILES_INSTALL_MODE"

setup_gitconfig () {
  git_local_config_file="git/gitconfig.local.symlink"
  git_local_config_file_example="git/gitconfig.local.symlink.example"

  if ! [ -f $git_local_config_file ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your GitHub author (full) name?'
    read -p "> " -e git_authorname
    user ' - What is your GitHub author email?'
    read -p "> " -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" $git_local_config_file_example > $git_local_config_file

    # When using WSL, make sure to use ssh.exe
    if [[ $(systemd-detect-virt) == 'wsl' ]]; then
      echo "Running on WSL, therefore setting ssh to ssh.exe to support 1Password SSH Auth"

      if ! $(grep -q "^\[core\]$" $git_local_config_file); then
        echo -e "\n[core]" >> $git_local_config_file
      fi

      if ! $(grep -q "^\s*sshCommand" $git_local_config_file); then
        sed -i -e '/^\[core\]$/a\\tsshCommand = ssh.exe' $git_local_config_file
      else
        sed -i -e 's/^\s*sshCommand.*/\tsshCommand = ssh.exe/' $git_local_config_file
      fi

    fi

    success 'gitconfig'
  fi
}


link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"

        if [[ $- == *i* ]]; then
          echo "... backing up since we are running non-interactively"
          action=b
        else
          read -n 1 action
        fi

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done

  if command -v zsh &> /dev/null
  then
    info 'cleaning up old dead symlinks (checking for matches):'
    zsh -c "cd $HOME && rm -- *(-@D)" || true
  fi

  success 'installed dotfiles'
}

install_vscodefiles () {
  info 'installing vscode files'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT/vscode" -maxdepth 1 -name '*.json' -not -path '*.git*')
  do
    if test "$(uname)" = "Darwin"
    then
      # info "installing macOS VS Code file: ${src} to ${dst}"
      mkdir -p "$HOME/Library/Application\ Support/Code/User/"
      dst="$HOME/Library/Application\ Support/Code/User/$(basename "${src}")"
      link_file "$src" "$dst"
    elif test "$(expr substr $(uname -s) 1 5)" = "Linux"
    then
      # info "installing linux VS Code file: ${src} to ${dst}"
      mkdir -p "$HOME/.config/Code/User/"
      dst="$HOME/.config/Code/User/$(basename "${src}")"
      link_file "$src" "$dst"
    else
      info "no compatible OS found to apply VS Code settings"
    fi
  done

  success 'installed vscode files'
}

make_zsh_default_shell

if [[ $- == *i* ]] || [ "$DOTFILES_INSTALL_MODE" = "minimal" ] ; then
  success "skipping Git configuration since we are running non-interactive or minimal"
else
  setup_gitconfig
fi

install_dotfiles
install_vscodefiles

# If we're on a Mac or Linux, let's install and setup homebrew.
if [ "$(uname -s)" == "Darwin" ] || [ "$(uname -s)" == "Linux" ]
then
  info "installing dependencies"
  if source bin/dot | while read -r data; do info "$data"; done
  then
    success "dependencies installed"
  else
    fail "error installing dependencies"
  fi
fi

add-key-value() {
    KEY="$1"
    VALUE="$2"
    FILE="$3"

    # Check if the file exists, if not, create it
    if [ ! -f "${FILE}" ]; then
        info "The file '${FILE}' does not exist. Creating the file."
        touch "${FILE}"
    fi

    # Check if the key exists in the file
    if grep -q "^${KEY}=" "${FILE}"; then
        info "The key '${KEY}' already exists in the file '${FILE}'. Updating its value to: ${VALUE}"
        # Update the value
        sed -i "s/^${KEY}=.*/${KEY}=${VALUE}/" "${FILE}"
    else
        info "The key '${KEY}' does not exist in the file '${FILE}'. Adding value: ${VALUE}"
        # Add the key-value pair
        echo "${KEY}=${VALUE}" >> "${FILE}"
    fi
}

set_tattoo () {
  info 'setting the tattoo'
  add-key-value "DOTFILES_INSTALL_MODE" $DOTFILES_INSTALL_MODE "$HOME/.env"
  if [[ $- == *i* ]]; then
    add-key-value "DOTFILES_INSTALL_NONINTERACTIVE" "true" "$HOME/.env"
  else
    add-key-value "DOTFILES_INSTALL_NONINTERACTIVE" "false" "$HOME/.env"
  fi
  add-key-value "DOTFILES_UPDATE_ON_LOGIN" "false" "$HOME/.env"

  add-key-value "DOTFILES_INSTALL_DATE" "$(date +"%Y-%m-%dT%H:%M:%S%:z")" "$HOME/.env"
  add-key-value "DOTFILES_UPDATED_DATE" "$(date +"%Y-%m-%dT%H:%M:%S%:z")" "$HOME/.env"
  success 'tattoo set'
}

set +e # Temp undo set -e so that we can catch the error
VALUE=$(get-key-value DOTFILES_INSTALL_DATE ~/.env)

if [ $? = 1 ]; then
  set -e
  set_tattoo
else
  set -e
  success 'tattoo already set before'
  add-key-value "DOTFILES_UPDATED_DATE" "$(date +"%Y-%m-%dT%H:%M:%S%:z")" "$HOME/.env"
fi

echo ''
echo '  All installed!'
