#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Install homebrew
# TODO: Move these checks to the brew install scripts & simplify
if test $(which brew) && [ "$BACKGROUND_JOB" != true ] && [ "$DOTFILES_INSTALL_MODE" = "complete" ]
then
  echo "> check brew installation"
  find ./homebrew -name install.sh | while read installer ; do sh -c "${installer}" ; done

  echo "› brew bundle"

  if [ "$(uname -s)" == "Darwin" ]
  then
    brew bundle --file=Brewfile-desktop
  else
    brew bundle
  fi
else
  echo "skipping brew install since we are running in background job or install mode is not complete"
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
